language: java

git:
  depth: 99999

jdk:
  - oraclejdk8

script:
  - ./buildsupport/gradlewrapper/gradlew clean build

after_success:
  - ./buildsupport/gradlewrapper/gradlew jacocoTestReport coveralls
