language: java

env:
  global:
    - COVERALLS_REPO_TOKEN=KaiaNcXBfP2cda4WAV2tMJyqepXXLei5l

jdk:
  - oraclejdk8

script:
  - ./buildsupport/gradlewrapper/gradlew clean build

after_success:
  - ./buildsupport/gradlewrapper/gradlew cobertura coveralls
